### ISSUE TITLE
[spelling] 7.6 Encoding Characters

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#101]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/encoding-characters.html#character-encodings

## Issue

The first "natural" in this paragraph is misspelled as "natrual".

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Fixed. Thanks.
