### ISSUE TITLE
[comment] 7.6.2.2 ASCII Encoding

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#102]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/encoding-characters.html#the-ascii-encoding

## Issue

Can we use a way to denote the pronunciation of the ASCII that doesn't include the word "ASS"? 

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Yep, I approve of the removal of improper language!  Fixed.
