### ISSUE TITLE
[grammar] 7.6.3 Character Encodings in JavaScript

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#103]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/encoding-characters.html#character-encodings-in-javascript

## Issue

There are 2 occurrences of "convert from X to Y" in this section. Because "convert" is a transitive verb, I suggest removing "from" for simplicity. 

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Fixed. Thanks.
