### ISSUE TITLE
[spelling | grammar] 7.7 Special Characters

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#104]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/special-characters.html#special-characters

## Issue

1) "occasionally" is misspelled as "occassionally"
2) "string" should be "strings" 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/61193935-f7cf5f00-a683-11e9-9ddc-e40c6ebcbdc9.png)

**Comment by jimflores5** [comment]
Fixed, thanks.
