### ISSUE TITLE
[Incomplete pages]

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#106]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/for-loops.html#flow-of-execution-of-the-for-loop

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/while-loops.html#beyond-for-loops

## Issue

There are two admonition boxes in the Loop chapter contain a TODO reference. We need to fill these spaces with content or remove the boxes. 
 - "Add 'worst practice' on optional brackets for single-line loops" (9.2.2).
 - 'Add “worst practice” on writing a while loop as a for loop.' (9.6.4).

**Comment by chrisbay** [comment]
I removed these directives for now, noting them in https://trello.com/c/Tu0Or5Vk
