### ISSUE TITLE
[Repl.it] Can't add spec folders and tests to LaunchCode repl

### ISSUE THREAD

**Issue by ryan-neal** [LaunchCodeEducation/intro-to-professional-web-dev#109]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/unit-testing/hello-jasmine.html#id1

## Issue

Not able to add test files to LaunchCode repl. (I definitely may have messed this up)

## (Optional) Screenshow

<img width="203" alt="Screen Shot 2019-07-21 at 1 22 24 PM" src="https://user-images.githubusercontent.com/7199083/61595283-d65a0000-abba-11e9-8cda-94f3013253ab.png">

**Comment by jimflores5** [comment]
Fixed the clarity issue.  The instructions are now more deliberate about forking the starter code, and screenshots were added to help guide the students through creating new files.
