### ISSUE TITLE
[comment] 7.8 Template Literals

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#116]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/template-literals.html#template-literals

## Issue

I'd like to make a suggestion for the organization of this content: start the section with the highlighted text in the screenshot below. That way "template literals", a higher level concept, can be introduced as a way to solve the problem of cumbersome string concatenation with varibles / expressions. The definition of "template literals" as written in the first sentence of this current section is also easier to understand after introducing the problem as a context. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62017452-4567c380-b17c-11e9-9cae-332c2377c320.png)

**Comment by jimflores5** [comment]
Good suggestion.

Fixed.
