### ISSUE TITLE
[clarify] 9.2 for Loops

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#125]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/for-loops.html#flow-of-execution-of-the-for-loop

## Issue

I don't understand what the Todo box at the end of this section asks the readers to do....

## (Optional) Screenshot

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62428960-d8997f80-b6cd-11e9-88c1-3884f5a5c940.png)

**Comment by jimflores5** [comment]
These boxes are a known item for the ed team. They will be fixed or removed.
