### ISSUE TITLE
[spelling] 9.3 Iterating Over Collections

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#126]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/iterating-over-collections.html#iterating-over-arrays

## Issue

"languages" is misspelled as "launguages" as a variable. 

## (Optional) Screenshot

![image](https://user-images.githubusercontent.com/13736167/62429009-91f85500-b6ce-11e9-9880-31fba77df36a.png)

**Comment by jimflores5** [comment]
Fixed. Thanks.
