### ISSUE TITLE
[bug] 9.4 Breaking Down the for loop

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#127]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/for-statement-breakdown.html#initial-expression
## Issue

The note box is missing code example. 

## (Optional) Screenshot

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62429177-ca009780-b6d0-11e9-8e38-e3a2bc98cfd2.png)

**Comment by jimflores5** [comment]
Fixed. Thanks.
