### ISSUE TITLE
[spelling] 9.5 The Accumulator Pattern

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#128]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/accumulator-pattern.html#adding-1-n

## Issue

"explicitly" is misspelled as "explicitely". 

## (Optional) Screenshot

![image](https://user-images.githubusercontent.com/13736167/62429346-46947580-b6d3-11e9-8812-9b1219a9ade2.png)

**Comment by jimflores5** [comment]
Fixed. Thanks.
