### ISSUE TITLE
[spelling] 9.6 while loop

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#129]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/while-loops.html#while-loop-syntax

## Issue

"eventually" is misspelled with only 1 letter l. 

## (Optional) Screenshot

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62429421-1f8a7380-b6d4-11e9-91ae-a60e5bfc8688.png)

**Comment by linwang929** [comment]
In the same section, right above 9.6.4, the word "all" is unnecessary. See screenshot: 

![image](https://user-images.githubusercontent.com/13736167/62429466-b9522080-b6d4-11e9-995f-e9ce52b933b6.png)

**Comment by linwang929** [comment]
There is a "todo" box in this section as well. Now I understand that the "todos" are mostly for ed team members.

**Comment by linwang929** [comment]
In 9.6.5 the following sentence misses an "and". It should be "The variable i is initialized to 0 and never updated". 

![image](https://user-images.githubusercontent.com/13736167/62429546-8bb9a700-b6d5-11e9-905b-d19346233806.png)

**Comment by jimflores5** [comment]
Fixed all issues (except for the TODO box).  Thanks.
