### ISSUE TITLE
[spelling] 10.1 Introduction to Functions

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#136]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/functions/intro.html#introduction

## Issue

"receiving" is misspelled as "receving". 

## (Optional) Screenshot

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62827750-5f9d9a80-bb9b-11e9-946f-c513bdfbdb6e.png)

**Comment by jimflores5** [comment]
Thanks.  Fixed.
