### ISSUE TITLE
[grammar] 10.1 Introduction

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#137]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/functions/intro.html#introduction

## Issue

I didn't find concrete grammar rules but when I learned the word "provide" there are 2 acceptable ways to use it: 1) provide someone/something with something and 2) provide something to someone/something. It's weird that while "provide" is similar in meaning with "give", I have not seen it used like without a preposition. I suggest adding "with" to the highlighted phrase, and the other "provide" later in the same paragraph. 

Also, the first sentence is also awkward in saying that "we must do something... if needed". We can change it into "When using a function that needs some input, we must provide it with those input."

## (Optional) Screenshot

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62827849-5e21a180-bb9e-11e9-9b8b-384865d91ad7.png)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
