### ISSUE TITLE
[clarify] 10.4 Function Input and Output

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#138]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/functions/function-input-and-output.html#using-return-is-optional

## Issue

I think it will make sentence more clear to change "if" to "though". 

## (Optional) Screenshot

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/62837967-80b5c800-bc3b-11e9-8579-15e6b5001e39.png)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
