### ISSUE TITLE
[Clarity]

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#144]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/exercises.html#exercises-booleans-and-conditionals

## Issue

In exercise 6, if the students code the ``if/else if`` statements in order from parts a - e, the tests will never reach the final check.

This was a deliberate choice to reinforce the idea that order is important when sequencing conditionals.  However, one of the TAs brought up a good point that problem 6 can discourage students who perceive it as a trick question.

We should consider how to rephrase the instructions for this question to more clearly to note that "order is important" and warn students that they will need to arrange the conditionals carefully.  Maybe something like, "HINT: You will need to code the conditionals in a different order than shown below."

## (Optional) Screenshot

![Screen Shot 2019-08-15 at 1 22 50 PM](https://user-images.githubusercontent.com/31870126/63116673-d356f300-bf5f-11e9-9f13-d9774c3253a2.png)

**Comment by gildedgardenia** [comment]
Pushed up a fix to the issue. Let me know what you think!

**Comment by jimflores5** [comment]
Nice work! This makes the students consider the proper order for ``if`` statements.

A few editing suggestions for the original, "Order is important when working with conditionals and the checks below are not in the order that you would code in. Please read each check carefully before coding and consider the order the checks should be in!"

1) Need a comma after "conditionals".
2) How about, "...and the checks below are not written in the correct sequence." (Eliminates the ending preposition).
3) How about, "Please read ALL of the checks before coding and then decide on the best order for the conditionals."
