### ISSUE TITLE
[COPY EDIT] Missing question mark

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#147]
## Permalink

https://github.com/LaunchCodeEducation/Fetch-and-JSON-Studio

## Issue

Question mark missing at the end of a question. It's a period instead.

**Comment by jimflores5** [comment]
The sentence itself was not actually a question.  I rephrased it to fix the ambiguity.

I also found and fixed a couple of other typos (this ---> the, below HTML ---> HTML below).

**Comment by gildedgardenia** [comment]
This was the wrong link! I screenshot the page and am reviewing it now!
