### ISSUE TITLE
[TypeScript] How about discussing functions in TS?

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#152]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/typescript/index.html#typescript

## Issue

The chapter talks about declaring variables, arrays, classes and interfaces in TS, and it also presents the differences between doing so in JS vs. TS.

Since the students need to code TypeScript functions in the Angular lessons, can we include a similar discussion about JS functions vs. TS functions?

## (Optional) Screenshot

![Screen Shot 2019-08-16 at 3 27 09 PM](https://user-images.githubusercontent.com/31870126/63196204-577da900-c03a-11e9-9c0a-9282af48705d.png)

**Comment by gildedgardenia** [comment]
New content has been merged in!
