### ISSUE TITLE
[Clarity] Phrasing in the More Promises section.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#156]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/fetch-json/asynchronous.html#more-promises

## Issue

After the sentence, "A promise can represent any future event," the meaning of the first paragraph becomes murky.  What idea are we trying to convey to the students?

Also, can we give a clearer example of a promise used for a non-HTTP event?  The phrasing makes it sound like the example should be self-explanatory, but it is not.

## (Optional) Screenshot

![Screen Shot 2019-08-18 at 12 11 41 PM](https://user-images.githubusercontent.com/31870126/63227906-6044bb00-c1b1-11e9-9628-a56d98319e8b.png)

**Comment by gildedgardenia** [comment]
Issue resolved!
