### ISSUE TITLE
Incorrect schedule in the Instructor's Note Wiki for Class 5

### ISSUE THREAD

**Issue by brclark** [LaunchCodeEducation/intro-to-professional-web-dev#164]
## Permalink

https://github.com/LaunchCodeEducation/intro-to-professional-web-dev/wiki/Class-5-(Functions)

## Issue

The instructor's notes for Class 5 mention in the *Announcements*:

Congrats on finishing your first graded assignment!
Next class, your second graded assignment will open up for you to start working on. You will have two weeks to do this assignment so be sure to start looking at it when it becomes available to you.

The first graded assignment will not be completed until after Class 6. Please remove this part from the announcements.

**Comment by gildedgardenia** [comment]
Thanks for letting us know! Fixed!
