### ISSUE TITLE
Confusing Assignment #1 Description/Format

### ISSUE THREAD

**Issue by brclark** [LaunchCodeEducation/intro-to-professional-web-dev#165]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/assignments/candidateQuiz.html

## Issue

Getting lots of confusion and questions from students regarding assignment #1 description. Here is what I'm finding.

Putting the Example Output *first* in the Assignment description causes students to immediately start writing code to produce the Example Output. No one is going through the whole Assignment page to find the [Minimum Viable Quiz - Part 1](https://education.launchcode.org/intro-to-professional-web-dev/assignments/candidateQuiz.html#part-1-minimum-viable-quiz).

Furthermore, I think there needs to be example output for [Minimum Viable Quiz](https://education.launchcode.org/intro-to-professional-web-dev/assignments/candidateQuiz.html#part-1-minimum-viable-quiz) so that students can complete Part 1 and understand that it is a building block for them to reach the final desired output.

The [Example Output](https://education.launchcode.org/intro-to-professional-web-dev/assignments/candidateQuiz.html#example-output) should be placed at the end of the Assignment description in order to show what the final product should look like after each Part has been completed in order.

**Comment by gildedgardenia** [comment]
Thanks for submitting this issue! The fix for this issue is now live!
