### ISSUE TITLE
Confusing/Incorrect Quiz question for Class 5

### ISSUE THREAD

**Issue by brclark** [LaunchCodeEducation/intro-to-professional-web-dev#166]
## Issue

A question in the quiz for Class 5 asks what the following function returns.

While I agree that it returns nothing, in practice and in repl.it, the function returns "undefined" when printing it's value. I had a student ask about this, also stating that they tried it out and got "undefined" as their answer. "Undefined" in the quiz is treated as the wrong answer though. I think this question should be rewritten.

## (Optional) Screenshot

![Screenshot 2019-08-27 13 38 50](https://user-images.githubusercontent.com/1033598/63799107-ff179880-c8d0-11e9-848f-ed4ddea5f623.png)

**Comment by gildedgardenia** [comment]
This has been fixed! Thanks for letting us know!
