### ISSUE TITLE
[Content revision] Interfaces

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#200]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/typescript/classes.html#interfaces

## Issue

The first paragraph states, "When we start working with Angular, you may see the ``interface`` keyword quite a bit." However, we do not use interfaces in any of the Angular examples, exercises, or studios.

## (Optional) Screenshot

![Screen Shot 2019-09-11 at 3 43 26 PM](https://user-images.githubusercontent.com/31870126/64733754-eef3e180-d4aa-11e9-8361-17ab9abb5d0f.png)

**Comment by gildedgardenia** [comment]
Possible resolution in branch `typescript-edits`

**Comment by gildedgardenia** [comment]
Issue resolved.
