### ISSUE TITLE
[COPY EDIT] Inconsistent syntax for interface use?

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#202]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/typescript/classes.html#interfaces

## Issue

The syntax shown in the generic use of an interface does not seem to match the more specific example.  Are lines 6 & 14 necessary in the Tiger and Lion classes?

## (Optional) Screenshot

![Screen Shot 2019-09-11 at 3 46 53 PM](https://user-images.githubusercontent.com/31870126/64734096-9709aa80-d4ab-11e9-80ce-1ed771b669f0.png)

**Comment by gildedgardenia** [comment]
Issue resolved.
