### ISSUE TITLE
[COPY EDIT] Figure revision

### ISSUE THREAD

**Issue by brclark** [LaunchCodeEducation/intro-to-professional-web-dev#204]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/scope/introduction.html#execution-context

## Issue

The chapter on Scope has an issue in the Execution Context section in 15.1.3. The example shows a variable declared in the global execution context and two functions, coolFunction() and coolerFunction() which are defined.

These functions are never called in the code snippet but the example description continues on describing what happens as if the two functions are called. The functions should be called somewhere to show how they are put on the execution context.

**Comment by jimflores5** [comment]
Resolved.  The figures have been updated, and explicit function calls were added to the code block.
