### ISSUE TITLE
[COPY EDIT] Typo in Assignment #3: Mars Rover

### ISSUE THREAD

**Issue by TJ-Owen** [LaunchCodeEducation/intro-to-professional-web-dev#205]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/assignments/mars-rover.html#requirements

## Issue

In Step 4 of the Requirements, "it's" is used when it should be "its" instead.

## (Optional) Screenshot

![Assignment__3__Mars_Rover_—_Introduction_to_Professional_Web_Development_in_JavaScript_documentation](https://user-images.githubusercontent.com/5385789/64982748-8d55bd80-d884-11e9-8e13-aefd67a117ce.gif)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
