### ISSUE TITLE
[COPY EDIT] Feedback for assignment 3.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#212]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/assignments/mars-rover.html

## Issue

TA Paul had this suggestion for the Rover assignment:
Regarding assignment 3, I thought of a new test case that wasn't covered in the material: "Generator watts should change values when changing rover mode from normal to low power". Right now we don't give students a reason to try to change that value in response to anything.

Instructor Ben:
There could be a clearer emphasis on writing one test at at time.
1. Write a _single_ test (it should fail),
2. Write the code to make that test pass,
3. Write the next test, etc. A number of students are reading the test descriptions and then trying to code all the tests at once.

Also, the third message test (screenshot) can be passed even without using an array of command objects as the argument.  Should the students consider the passing case to be just having a second parameter sent to the function, having a non-empty array sent to the function, or have an array of Command objects sent to the function?

Students:
1) Seems to be an abrupt shift from specific steps to unguided instructions.
2) One student wrote his own interpretation of the instructions.  We should review that pdf.

## Screenshot (optional)

![Screen Shot 2019-09-23 at 3 25 14 PM](https://user-images.githubusercontent.com/31870126/65459920-7c71f280-de16-11e9-87dc-f9812806389d.png)

**Comment by CarlyLanglois** [comment]
closed, info added to trello card: https://trello.com/c/FI8Bd9Vd/245-assignment-3-feedback
