### ISSUE TITLE
[COPY EDIT] "Firefox" not "Firebox"

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#216]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/git/repositories-and-commits.html#respositories-and-commits

## Issue

"Firefox" is misspelled in the line, "Open Firefox's dev tools."

**Comment by jimflores5** [comment]
Fixed the Firebox spelling issue in the Making Headlines studio.

Also fixed the page heading spelling issue in the Repositories and Commits page.
