### ISSUE TITLE
[COPY EDIT] "cafes.sql" not "cafes.json"

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#217]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/appendices/terminal-commands/terminal-commands-tutorial.html?highlight=cafes%20sql#touch-command

## Issue

The chapter refers to them using ``touch`` to create a file called ``cafes.sql``, but the diagram calls it ``cafes.json``.

## (Optional) Screenshot

![Screen Shot 2019-09-21 at 3 08 59 PM](https://user-images.githubusercontent.com/17087389/65632635-c4705100-df9f-11e9-8928-275635d6ef36.png)

**Comment by jimflores5** [comment]
Fixed.
