### ISSUE TITLE
[COPY EDIT] "touch my_first_file.txt" not "touch my_first_file"

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#218]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/terminal/exercises.html#exercises-terminal

## Issue

"touch my_first_file.txt" not "touch my_first_file"

## (Optional) Screenshot

![Screen Shot 2019-09-21 at 4 03 37 PM](https://user-images.githubusercontent.com/17087389/65634088-18306980-dfa3-11e9-9124-8015f7a3b4f1.png)

**Comment by jimflores5** [comment]
Fixed.
