### ISSUE TITLE
[COPY EDIT] Move installation instructions for Terminal earlier in the chapter.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#220]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/terminal/index.html#terminal

## Issue

Some of the students feel like they missed the link for getting Terminal ready on their computers. Currently, the link to the installation appendix is in the chapter exercises, but it would be helpful if it appeared earlier in the chapter.

## (Optional) Screenshot

(If helpful, add a screenshot.)

**Comment by CarlyLanglois** [comment]
addressed and resolved in #224
