### ISSUE TITLE
[COPY EDIT] Update section heading?

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#223]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/dom-and-events/javascript-in-the-browser.html#inline-javascript

## Issue

A student noted that the heading says "Inline JavaScript", and he argues that it should actually read "Internal JavaScript".

## (Optional) Screenshot

![Screen Shot 2019-10-07 at 8 29 53 AM](https://user-images.githubusercontent.com/31870126/66316123-b0e8b280-e8dc-11e9-8f1e-129836256488.png)

**Comment by CarlyLanglois** [comment]
i don't think this is really an issue, as this is pretty widely accepted as what inline javascript is, the use of a script tag without a src
