### ISSUE TITLE
[COPY EDIT] Grading and Student Progress - Warning Do Not Edit Assignment section unclear

### ISSUE THREAD

**Issue by evanharmon1** [LaunchCodeEducation/intro-to-professional-web-dev#230]
## Permalink
https://github.com/LaunchCodeEducation/intro-to-professional-web-dev/wiki/Grading-and-Student-Progress#warning-do-not-edit-assignment

## Issue
The section that explains the circumstances in which a teacher could edit the assignment for everyone else including the students is unclear to me and others in our cohort. It also mentions a student preview mode in repl.it that I could not replicate. Due to there being some differences between the online book's repl.it's and the canvas repl.it's this makes things difficult since I'm not confident I will not be editing the assignments by doing the canvas version of the repl.it's.

**Comment by evanharmon1** [comment]
E.g., a student asks about "the arrays exercises, unit 3, part 1, part B.5" (from the canvas version of repl.it) but on the online book version, it is chapter 8.5. Exercises: Arrays, #2 problem b. Ideally, I could just do the canvas version so I am doing the same version. Can you clarify how to use the canvas version without modifying the students' exercises?

**Comment by gildedgardenia** [comment]
Hi Evan! Thanks for letting this know! Edits to the directions with more clarity on how you can do this are in progress and we will let you know when those edits are merged in!

**Comment by gildedgardenia** [comment]
Hi Evan! Additional instructions on how to enter Student Preview mode in repl.it have been added to the wiki. Thanks again!
