### ISSUE TITLE
[COPY EDIT] Check variable assignments in TypeScript exercises

### ISSUE THREAD

**Issue by CarlyLanglois** [LaunchCodeEducation/intro-to-professional-web-dev#232]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/typescript/exercises.html

## Issue

spacecraft name may need to be checked for consistency. also possible variable re-declaration in starter code

## (Optional) Screenshot

<img width="735" alt="Screen Shot 2019-10-14 at 9 12 50 AM" src="https://user-images.githubusercontent.com/20828430/66757927-d3da1000-ee62-11e9-8704-b7cc372c3bf0.png">

https://slack-files.com/TM1HDJCR4-FPBSC981W-e3848a2dee

https://slack-files.com/TM1HDJCR4-FPBSEM42C-669d1a44ef

https://slack-files.com/TM1HDJCR4-FP0C99X3M-8ba281a48b

**Comment by CarlyLanglois** [comment]
ok, looked into this a bit. the exercises have the students create multiple .ts files that build upon the same solution. Apparently TypeScript will not treat these as separate modules as node does. so this creates errors in the editor because some of the variables are defined multiple times throughout the files. this doesn't actually prevent the individual ts files from compiling, so students can still run their solutions.
That said, we can also re-write this set of exercises to be built in just one ts file, which would solve this issue. 
I'm leaving this open so I can return to this idea!

**Comment by jimflores5** [comment]
Resolved.
