### ISSUE TITLE
[COPY EDIT] Angular polyfills.ts Fix

### ISSUE THREAD

**Issue by CarlyLanglois** [LaunchCodeEducation/intro-to-professional-web-dev#235]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/angular-lsn1/file-structure.html

## Issue

Figure shows a file called polyfill.ts but it should be named polyfills.ts. not sure where this image lives now to edit it so, putting this up here to be done at some point.

## (Optional) Screenshot

<img width="729" alt="Screen Shot 2019-10-14 at 4 58 44 PM" src="https://user-images.githubusercontent.com/20828430/66786184-17556e00-eea5-11e9-881a-d8c0932892cb.png">

**Comment by jimflores5** [comment]
Recreated the image and fixed the typo.
