### ISSUE TITLE
[COPY EDIT] Misssing 'of'

### ISSUE THREAD

**Issue by evanharmon1** [LaunchCodeEducation/intro-to-professional-web-dev#251]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/arrays/arrays-are-like-strings.html

## Issue

"The figure below demonstrates an array named languages." should be "The figure below demonstrates an array of named languages."

## (Optional) Screenshot

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Fixed, thanks.  We will fold this into our next weekly set of updates.
