### ISSUE TITLE
[COPY EDIT] Inconsistent/confusing wording on Array Methods

### ISSUE THREAD

**Issue by evanharmon1** [LaunchCodeEducation/intro-to-professional-web-dev#252]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/arrays/array-methods.html

## Issue

"To see detailed examples for a particular method, control-click (or right-click) on its name." is inconsistent - they perform 2 different actions, not to mention the actions are different on different platforms. I believe it should just say something like "Follow the link for each method name to see detailed examples."

## (Optional) Screenshot

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Thanks.  Keep the feedback coming!
