### ISSUE TITLE
[COPY EDIT] Misleading sentence on multi-dimensional array methods

### ISSUE THREAD

**Issue by evanharmon1** [LaunchCodeEducation/intro-to-professional-web-dev#253]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/arrays/multi-dimensional-arrays.html

## Issue

"Both the inner and outer arrays in a multi-dimensional array are still altered with array methods." is vague and misleading. E.g., the example following this statement shows that the inner array is NOT altered by an array method since it depends on which array the method is called on. I think a better statement would be "Both the inner and outer arrays in a multi-dimensional array can still be altered with array methods as long as bracket notation is used correctly."

## (Optional) Screenshot

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Rephrased.  Thanks.
