### ISSUE TITLE
[COPY EDIT] Equality of instances

### ISSUE THREAD

**Issue by evanharmon1** [LaunchCodeEducation/intro-to-professional-web-dev#258]
## Misleading Explanation of instance equality
I think this part explaining instances is misleading: "However, the values assigned to each key differ. For this reason, objects created with the same class are NOT equal." Objects created with the same class are not equal because they are different instances and point to different places in memory. The values of the keys could be the same and they still would not be equal. Is that not correct? If that is correct I think that part should be reworded. Conceptually, it is intuitive as well, in that a blueprint for a car would create 2 identical cars of the same size, etc but they would still be different cars/not equal. 

## (Optional) Screenshot

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
This section was revised to address comparing objects.
