### ISSUE TITLE
[COPY EDIT] Frameworks example

### ISSUE THREAD

**Issue by r-spell** [LaunchCodeEducation/intro-to-professional-web-dev#264]
## Permalink
Permalink is my enemy, I don't know if this works or not, [8.1.1. Declaring an Array](https://education.launchcode.org/intro-to-professional-web-dev/chapters/arrays/arrays-are-like-strings.html#declaring-an-array)

## Issue
Someone else actually brought this issue to my attention but **technically** React is a Library not a Framework but the example at the end of this section makes it seem like React is a Framework. 

## (Optional) Screenshot
<img width="976" alt="Screen Shot 2020-01-30 at 8 41 29 PM" src="https://user-images.githubusercontent.com/28410016/73508447-9e214e80-43a1-11ea-9482-80671944d7e6.png">

**Comment by jimflores5** [comment]
After much internal discussion and multiple Google searches, we have decided to keep the text as-is.  The argument of React being a framework vs. library gets too far into the nitty-gritty details, and valid points of view can be found for both sides.
