### ISSUE TITLE
Suggestions for Mars Rover assignment

### ISSUE THREAD

**Issue by usyrle** [LaunchCodeEducation/intro-to-professional-web-dev#276]
I had some ideas for tweaking Mars Rover for next cohort, sharing in case any of them are helpful!

- TA_Bruce had an idea to add a status.js or similar to create a class (and tests) around the results returned by receiveMessage in Rover, I think that might help students understand it a little better! The array-of-anonymous-objects has thrown a few of my students off, since the prop is already inside an anonymous object.

- I've had a few students struggle with testing individual object properties vs a whole object; when dealing with anonymous objects, assert.strictEqual fails with "objects identical but not reference equal" and students struggle to understand what that even means. I wonder if the assignment language can be more explicit that students should test props and not whole objects? I've seen it occur most in tests 9 and 10.

- I know you have little control over this, but I think it's rough that this assignment was originally going to be due the same night as the git merge studio. I personally think it's a very important one since I've had lots of LC students who simply don't understand git usage, which makes it hard for them to submit or update assignments through the rest of the class. But, with the Rover hanging over their heads, the students who are behind are likely to prioritize it over the studio, when they are probably the ones who most need some hands-on time with git. :woman-shrugging: 

- I really like what was done with test 9 and test 10, making the student handle multiple commands with test 9 then sort-of setting them up to break it when passing in a literal command with test 10 - I think it's a good demonstration of why tests are useful. I almost wonder if Tests 11 and 12 are better follow-ons to 9 though; test 10 is the hardest one by far, and my gut feeling is that it could be incredibly frustrating to get test 10 to pass only to see 9 fail when it used to work.

- I think it might be a good idea to have an additional TDD studio before Mars Rover is due; personally, I think it'd be a good lesson to have the students write the tests for a much earlier studio. I don't think many students realize that using repl.it classroom is literally the inverse of what they're doing with TDD, so getting to write the tests and bringing back a 'solved' studio might make the lightbulb go off.

- Most radical idea yet: it might be valuable to do a TDD studio using 'antagonistic pairing' - pair students a la git merging studio, but make one student only write tests then the other student only write code to solve it. A Fizzbuzz-style question might be good for that - test for 3, then for 5, then for 15.

As usual, thanks for all your hard work!

**Comment by CarlyLanglois** [comment]
@usyrle thank you these are very helpful suggestions. we have some upcoming improvements and changes so I'm closing your issue
