### ISSUE TITLE
Fix description of remainder operator

### ISSUE THREAD

**Issue by kphaldeman** [LaunchCodeEducation/intro-to-professional-web-dev#280]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/operations.html#arithmetic-operators

## Issue

It is mentioned here that the JavaScript operator % is the modulo operator (a.k.a. the remainder operator).  JavaScript does not have a modulo operator, it ONLY has the Remainder operator.  The difference is subtle, but there is a difference.  It is a long and convoluted conversation (see here: https://2ality.com/2019/08/remainder-vs-modulo.html).  It may confuse the new developer more, and it may not be worth changing, but it is a nit.  :-)

## (Optional) Screenshot

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
We wrestled with the best way to address your valid point, but ultimately decided to keep the current text in place.  As you mentioned, the difference is subtle.  We feel that the students will be able to resolve the discrepancy between modulo vs. remainder in their future jobs if the need arises.
