### ISSUE TITLE
[COPY EDIT] Classes chapter exercises 

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#285]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/classes/exercises.html#exercises-classes

Slack post: https://stlcccodecampmay2020.slack.com/archives/D0143SP50U9/p1590177070006200

## Issue

An instructor made the following suggestions after fielding questions from students:

Have some feedback regarding the textbook descriptions for Ch 18 exercises for classes.There was lots of confusion in our class due to some of the requirements being left vague. I figured the instructions were left somewhat vague by intention, but there are a few places where it may be too vague.

1) Construct three classes that hold the information needed by headquarters as properties. Also, each class needs two methods that update the book's property if the book needs to be discarded.
- Need more clarification on what two methods means. Based on your solution in gitlab, the Book class only has one method, the constructor. Is the constructor for each of these classes meant to count as a method?
- Manual has one method which is dispose() and Novel has two methods which are dispose() and checkout() .  There needs to be a bit more clarity in that phrasing "each class needs two methods"
- Also it is unclear if students should be directed to use the same name for the dispose method in Novel and Manual . If that is something that is desired, I think there needs to be more clarification in the description.

5) The other book has been checked out 5 times since you first created the object. Call the appropriate method to update the number of times the book has been checked out.

- This is the first place in the assignment description that vaguely mentions that Novel should have a second method which allows you to update the number of checkouts. I think it should be mentioned earlier that this type of functionality is expected in the Novel class

**Comment by gildedgardenia** [comment]
Instructions clarified!
