### ISSUE TITLE
[Solution Code] Assignment 5 page reload issue with successful data validation.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#288]
## Permalink

Assignment 5:
https://education.launchcode.org/intro-to-professional-web-dev/assignments/launch-checklist.html

GitLab solution:
https://gitlab.com/LaunchCodeEducation/lc101-solutions-unit1/-/tree/master/assignments/assignment5

Slack conversation:
https://stlcccodecampmay2020.slack.com/archives/D0143SP50U9/p1591653630002800

## Issue

From an instructor:
"For assignment #5 Launch Checklist Form, what should be the functionality when the user submits the form correctly?
1) If there is an issue, we call `preventDefault` and display an alert with what is wrong, as well as update the status div of HTML.
2) If there is NO issue, the form should be submitted and the status should be updated. However, when the form gets submitted, it reloads the page and causes any updates to the `launchStatusCheck` to disappear. How should their solution handle a successful submission of the form?

In the solution in GitLab, I notice that `event.preventDefault()` is called regardless of whether the form is submitted with valid data, on line 2. Is this the suggested way to preserve the status div at the bottom of the page? I would imagine that we would not call `event.preventDefault` in this case generally, because the form should be submitted successfully.

If `preventDefault` is not called, then the form submission will reload the page and therefore set the `launchStatusCheck` div to hidden again. I'm unclear on how to set that div and its data after the page has reloaded due to a successful form submission. I think I understand why `preventDefault` is used in both the success and the error case for this solution. But I've been advising students that they should only call `preventDefault` if the form has invalid data.

**Comment by chrisbay** [comment]
After looking into this, I don't think there's any issue with the solution code or the assignment requirements. I do, however, think that the guidance around how and when to use `preventDefault` could be clearer. I'm going to take a stab at improving this.

**Comment by chrisbay** [comment]
Addressed in #333
