### ISSUE TITLE
[COPY EDIT] Confusing sentence in HTML chapter

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#307]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/css/structure.html#css-examples

## Issue

Sentence in admonition about resizing headings is confusing to some students.

**Comment by chrisbay** [comment]
This is actually on this page: https://education.launchcode.org/intro-to-professional-web-dev/chapters/html/tags.html#tags-to-know
