### ISSUE TITLE
[COPY EDIT] DOM and Events Exercises

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#315]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/dom-and-events/exercises.html#exercises-the-dom-and-events

## Issue

From an LC101 instructor:
The use of `window.onload = init` is not referenced in the reading material for this section so it is confusing to use it for the first time in an exercise. For context, the reading uses `window.addEventListener("load", function() {}` instead.

https://education.launchcode.org/intro-to-professional-web-dev/chapters/dom-and-events/event-types.html#event-types

## Screenshot

![Screen Shot 2020-12-01 at 10 30 06 AM](https://user-images.githubusercontent.com/31870126/100768223-3c19e700-33c0-11eb-98f7-4d231f9ee8b6.png)

**Comment by chrisbay** [comment]
Fixed by #330
