### ISSUE TITLE
Angular 1 to Angular 2 Studio starter code

### ISSUE THREAD

**Issue by CarlyLanglois** [LaunchCodeEducation/intro-to-professional-web-dev#319]
From @jamesqquick 
James - Instructor  7:44 PM
For Angular 1 studio, after cloning the repo, they were asked to generate a new angular project. This creates a nested repository inside of the root repo. Then, when switching to the studio-2 branch, the original project is still inside of the root repository which becomes extremely confusing. My recommendation is to include the beginner Angular files in studio-1 so that we aren’t creating nested repositories. A little hard to explain, so let me know if you need more clarification, but this is extremely confusing and hard to debug for students/

**Comment by jimflores5** [comment]
This issue was addressed, and corrections to the Angular studio were merged into master.
