### ISSUE TITLE
Search functionality is broken

### ISSUE THREAD

**Issue by chrisbay** [LaunchCodeEducation/intro-to-professional-web-dev#353]
The recent updates to jQuery 1.12.4 and Bootstrap 3.4.1 seem to have broken the search functionality. I'm getting a 404 for those fiies (below the `_static/` directory), even after a hard refresh. Looking at the repo, I only see the old versions below `_static/`.

Students are experiencing this as well, across different browsers.

**Comment by gildedgardenia** [comment]
Hi Chris! We have fixed the issue!
