### ISSUE TITLE
Unit Testing Studio: Misnamed file type causes tests to not run

### ISSUE THREAD

**Issue by cgeffre** [LaunchCodeEducation/intro-to-professional-web-dev#385]
### URL: Path to Bug

https://replit.com/@launchcode/UnitTestingStudio#index.js

### Nature of Bug

In unit testing studio repl (https://replit.com/@launchcode/UnitTestingStudio#index.js), the launchcode spec file is launchcode.spec.json. This needs to be changed to launchcode.spec.js in order to run npm test. I imagine this bug occurred after creating the jasmine.json file (which is correct).

Side note - studio instructions and textbook don't mention npm test currently; this may be a useful addition to the studio instructions.

**Comment by gildedgardenia** [comment]
Thank you for submitting this bug! We will let you know when we have fixed it!

**Comment by gildedgardenia** [comment]
This issue has been fixed!
