### ISSUE TITLE
[clarify] 1.1 Why Learn to Code

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#47]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/introduction/why-learn-to-code.html#why-learn-to-code

## Issue

The first two sentences as written don't transition very well. The first sentence reads like a rhetoric question but the second sentence talks about something else instead of answering it. I understand that they are meant to say that "computer" and "technology" are both ubiquitous but I think the transition can be improved. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/59566163-bf574980-9021-11e9-8a34-6f00e83a0b93.png)

**Comment by welzie** [comment]
@linwang929 Do you have a suggestion for replacing them? I'm struggling to come up with something different.

**Comment by linwang929** [comment]
My thought to revise it in a most simple way is to add "What do you use it for?" between those two sentences. That way the following sentence "Maybe you use a computer ..." sort of answers both of those questions.
