### ISSUE TITLE
[spelling] 4.1 Values and Data Types

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#50]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/values-and-data-types.html#values-and-data-types

## Issue

1) "enclosed" is misspelled as "encolosed" (Screenshot 1)
2) "Hello" is misspelled as "Helo" in the first line in Screenshot 2
3) "Hello" is misspelled as "Hellow" in the note in Screenshot 2
4) In the Note, I believe the first sentence should say 'prints out the data type of "Hello, World!" to the console.' 
5) In the Note, the second Hello, World! misses a double quote
6) In the Note, the third Hello, World! should have a double quote after the exclamation instead of before. 

## (Optional) Screenshow

![image](https://user-images.githubusercontent.com/13736167/59646551-1140c200-913d-11e9-85bb-22495d77cecd.png)
![image](https://user-images.githubusercontent.com/13736167/59646888-7f39b900-913e-11e9-9a72-65df0bc5466d.png)

**Comment by ryan-neal** [comment]
On the line typeof "Hellow, World"!, the ! should be inside the quotations

**Comment by r-spell** [comment]
I also think it would be clearer if the first sentence in the note said something like 'prints out `string`, the data type of "Hello, World!" to the console.'
