### ISSUE TITLE
[spelling] 4.3 Variables

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#51]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/variables.html#variables

## Issue

1) Right above Heading 4.3.1, "formally" is misspelled as "formaly". 
2) Under Heading 4.3.1, there is a segment that needs to be edited to fit into the sentence. (Screenshot 1). 
3) In the first Warning under Heading 4.3.1, I believe there should be an example of using var to declare a variable (Screenshot 2). 
4) The Tip box under Heading 4.3.1 seems unfinished - please let me know if I should wait to review this chapter.... 
5) Under Heading 4.3.2 the first Example has a redundant "same" (Screenshot 3)
6) Under Heading 4.3.3 there is a missing "to" (Screenshot 4) in "asking the computer to remember things"

## (Optional) Screenshow
Screenshot 1
![image](https://user-images.githubusercontent.com/13736167/59648079-510aa800-9143-11e9-9d7f-0ed2971e81f9.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/13736167/59648172-beb6d400-9143-11e9-8499-455e23d4f617.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/13736167/59648509-e35f7b80-9144-11e9-9b7d-bf602577d9bb.png)

Screenshot 4
![image](https://user-images.githubusercontent.com/13736167/59648655-74365700-9145-11e9-9d0d-3613b821e9eb.png)

**Comment by ryan-neal** [comment]
I was confused by the tip under 4.3.1 

"To avoid confusion when reading or writing code, say to yourself

or

Don’t say"

**Comment by welzie** [comment]
Ed team notes about issue #3 above. There was supposed to be a code example using `var`, but for some reason it wasn't showing up.

I tried a few random things. Finally changing the to `.. admonition:: Warning` instead of `.. warning::` made the code block show up. Somehow `.. warning::` was completely preventing the source code from being rendered into HTML.

**Comment by welzie** [comment]
@ryan-neal @linwang929 We apparently have a bug in our code that generates the "tip/note/warning" sections. Those sections are currently removing any code we try to show inside of them. I have fixed a few, but be on the look out for that going forward. The Ed team will have to find a long term solution for that.
