### ISSUE TITLE
[Spelling] 4.4.2.3

### ISSUE THREAD

**Issue by ryan-neal** [LaunchCodeEducation/intro-to-professional-web-dev#53]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/more-on-variables.html#camel-case-variable-names

## Issue

conventional and impolite are misspelled in the example box
because is misspelled in the note above 4.4.3

**Comment by linwang929** [comment]
Two consecutive "another" in the same section (highlighted below)
![image](https://user-images.githubusercontent.com/13736167/59968624-3436f180-9502-11e9-8475-022df6d08f75.png)
