### ISSUE TITLE
[clarify] 6.8.1. Debugging Practice

### ISSUE THREAD

**Issue by r-spell** [LaunchCodeEducation/intro-to-professional-web-dev#57]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/exercises.html#debugging-practice

## Issue
In 5e, students are asked to "Refactor" the code but there's not really an explanation of what refactoring means until chapter 14, maybe give the directions in more general terms, like maybe "update" or "fix". (I did a search for "refactor" in the term search and see this is an issue in other Pre-chapter-14 chapters as well)

## (Optional) Screenshot

<img width="1139" alt="Screen Shot 2019-06-19 at 11 00 49 PM" src="https://user-images.githubusercontent.com/28410016/59817912-5143a880-92e7-11e9-963f-5f3d3a85eda5.png">

<img width="971" alt="Screen Shot 2019-06-19 at 11 03 04 PM" src="https://user-images.githubusercontent.com/28410016/59817923-61f41e80-92e7-11e9-9c98-ba3c710e88fd.png">

**Comment by jimflores5** [comment]
Fixed. Thanks.
