### ISSUE TITLE
[clarify] 5.3.1.2. Logical OR

### ISSUE THREAD

**Issue by r-spell** [LaunchCodeEducation/intro-to-professional-web-dev#59]
## Permalink
https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/logical-operators.html#logical-or

## Issue
1) In the warning box, I think you should either not use the words "bitwise operators" and "binary operators" or introduce which is which with those labels a little clearer. Like maybe you could even have a li'l table or something that is like 

> Bitwise Operators:  | & 
> Binary Operators: || && 

Before or after the main text inside that "Warning" box. 

2) **Also** 🤔 I think that using a & instead of a && (etc.) would produce a "logic error" . Maybe it should say "The single symbols & and | are themselves valid JavaScript operators, so accidentally leaving off one of the symbols when typing && or || will not result in an error _message_" ?

## (Optional) Screenshot
<img width="998" alt="Screen Shot 2019-06-20 at 12 00 24 AM" src="https://user-images.githubusercontent.com/28410016/59819821-1e9dae00-92ef-11e9-87e0-e87c4fdc8c44.png">

**Comment by jimflores5** [comment]
Thanks.  Part of the problem was that some of the info you wanted disappeared from the box due to an rst typo.  Good catch!

**Comment by r-spell** [comment]
Ah! makes sense
