### ISSUE TITLE
[Clarify] 4.4 More On Variables

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#62]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/more-on-variables.html#creating-constants-with-const

## Issue

I read the highlighted section below and am not sure I understand the "downside". Is it possible for someone on the education team to walk me through it? 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/59968498-60517300-9500-11e9-9bc7-8ebdd9a96a2b.png)

**Comment by jimflores5** [comment]
Rephrased the paragraph to clarify the point being made.
