### ISSUE TITLE
[spelling] 4.4.3 Keywords

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#63]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/more-on-variables.html#keywords

## Issue

"different" is misspelled in the Warning box. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/59968678-14ec9400-9503-11e9-8f12-5aecf80ba24d.png)

**Comment by jimflores5** [comment]
Fixed!
