### ISSUE TITLE
[clarify] 4.6.2 Arithmetic Operators

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#64]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/operations.html#arithmetic-operators

## Issue

1) In the screenshot below, can we change "A number" into "An integer"
2) In the Note box (also in the screenshot), can we clarify by adding "(not including b)" after "between 0 and b"? Because the value from a modulus could be 0 but not b. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/59968793-33ec2580-9505-11e9-95f1-12d9d20aff86.png)

**Comment by jimflores5** [comment]
Clarifications applied.  Thanks.
