### ISSUE TITLE
[clarify] 4.6.3 Order of Operations

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#65]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/operations.html#order-of-operations

## Issue

Does "both division operators" include modulus? or does it mean something else? 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/59968855-7eba6d00-9506-11e9-8db7-9e41969c5cba.png)

**Comment by jimflores5** [comment]
Clarified. "Multiplication, division, and modulus operators..."
