### ISSUE TITLE
[formatting] 4.7.2 Compound Assignment Operators

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#66]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/other-operators.html#compound-assignment-operators

## Issue

The division assignment expression is formatted differently in the table. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/59980504-905e4c00-95bc-11e9-9e3a-7dee7fc8f2a4.png)

**Comment by jimflores5** [comment]
Fixed. Thanks.
