### ISSUE TITLE
[Clarify] Strings Chapter Exercise 4

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#67]
## Issue

Chapter 7 Exercise 04
d. Use a template literal to print, "The DNA string is ___ characters long."
However, the submission seems to want it to say "The DNA strand...

As reported by Kate

**Comment by jimflores5** [comment]
Fixed.  Simple typing inconsistency between the chapter text, code comment and testing check.
