### ISSUE TITLE
[Clarify] Strings and Arrays Studio Part 3

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#69]
## Issue

Kate let me know that in the third part of the studio, the lettered instructions don’t match up with the lettered steps in the input window. Like b doesn't line up with b and all that and onward, it's pretty easy to overlook but can trip someone up. Also, the instructions tell you to query the user for “Select cabinet:” but the validation checks for “Select a cabinet:” in step d and gives you a false otherwise.

It could also be helpful to be explicit about splitting with comma spaces in part three and I can see a lot of people going through the steps and getting things wrong.

Submitted by Koko

**Comment by jimflores5** [comment]
Good catch, thanks.  The comma-spaces have been removed from the given strings, and the other inconsistencies have been corrected.
