### ISSUE TITLE
[spelling] 4.9 Exercises

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#71]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/data-and-variables/exercises.html

## Issue

1) In Exercise 2, "it's" should be "its" (possessive pronoun)
2) In Exercise 4, "part c" should be "Part 3"

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Fixed. Thanks.
