### ISSUE TITLE
[bug | spelling] 5.1.3.1 Comparison Operators

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#72]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/booleans.html#comparison-operators

## Issue

1) "Warning" box is not displaying code properly. @welzie 
2) "surprised" is misspelled.

## (Optional) Screenshow

![image](https://user-images.githubusercontent.com/13736167/60231225-2533a480-985e-11e9-9c12-14a1943f93cc.png)

**Comment by jimflores5** [comment]
Fixed.
