### ISSUE TITLE
[COPY EDIT] Make edits consistent between Codio, Repl.it classroom and book.

### ISSUE THREAD

**Issue by jimflores5** [LaunchCodeEducation/intro-to-professional-web-dev#74]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/exercises.html#exercises-booleans-and-conditionals

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/exercises.html

https://education.launchcode.org/intro-to-professional-web-dev/chapters/arrays/exercises.html

Etc.

## Issue
Based on feedback from the pilot class and from us as we reviewed the exercises and studio activities, we made changes to the instructions for Repl.it classroom and Codio. We need to copy those improvements to the book content as well.

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by CarlyLanglois** [comment]
taking this one

**Comment by CarlyLanglois** [comment]
this is lengthy so it's getting tied to a trello card for division of labor!

https://trello.com/c/F5FO65Gc/166-epiciss-74-address-book-replit-text-discrepancies-in-exercises-studios

we'll also address addressing these when we do a weekly 'systems check' to test out class-specific material before upcoming class material is published
