### ISSUE TITLE
[Incorrect question] 9.4.2

### ISSUE THREAD

**Issue by ryan-neal** [LaunchCodeEducation/intro-to-professional-web-dev#77]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/loops/for-statement-breakdown.html#check-your-understanding

## Issue

I think I may have made a mistake answering this question, but I can not see how the loop could run more than 6 times or how any of the bottom answers are correct. Should the iterator have been i + 2?

**Comment by jimflores5** [comment]
Yep.  Wrong possible answers.  Thanks.

I've updated the questions to fit the code.
