### ISSUE TITLE
[spelling] 10.4

### ISSUE THREAD

**Issue by ryan-neal** [LaunchCodeEducation/intro-to-professional-web-dev#78]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/functions/function-input-and-output.html#using-return-is-optional

## Issue

In the second paragraph, there is a word usefuless that I think should be useless.

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Fixed. Thanks.
