### ISSUE TITLE
[grammar] 5.3 Logic Operators

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#80]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/logical-operators.html#logical-operators

## Issue

The comma highlighted below should be removed. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60435853-38cd6b00-9bd0-11e9-93bc-198965f37b62.png)

**Comment by jimflores5** [comment]
Removed.  Thanks.
