### ISSUE TITLE
[grammar] 5.3.2 Operator Precedence

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#81]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/logical-operators.html#operator-precedence

## Issue

1) "expression" should be plural in the highlighted sentence. 
2) I am wondering whether we encourage students to use parentheses (I believe we did in an earlier section). If so, I suggest reversing the order of this sentence: "While parentheses are not strictly necessary due to default operator precedence, they make expressions more readable and we encourage you to use them in complicated expressions."

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60436732-48e64a00-9bd2-11e9-8693-e9df4ec3a07d.png)

**Comment by jimflores5** [comment]
Nice suggestion on the phrasing.  I made the fixes.
