### ISSUE TITLE
[bug?] 5.4.1 if Statements

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#82]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/conditionals.html#if-statements

## Issue

I am not sure what to expect, but the "Todo" box seems to miss something... 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60437847-d9258e80-9bd4-11e9-9734-ae5032ea3c48.png)

**Comment by jimflores5** [comment]
Fixed. Thanks.
