### ISSUE TITLE
[code error] 5.4.3 else if Statements

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#83]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/conditionals.html#else-if-statements

## Issue

In the first example, we need to add console.log() to the code block after "else" clause

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60438133-96b08180-9bd5-11e9-93d6-f8c557ae4b35.png)

**Comment by jimflores5** [comment]
Fixed. Thanks.
