### ISSUE TITLE
[grammar] 5.5 Nested Conditionals

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#84]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/booleans-and-conditionals/nested-conditionals.html#nested-conditionals

## Issue

In the "Try it" box, an article "a" is unnecessary. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60438614-bbf1bf80-9bd6-11e9-975f-9690e795ef96.png)

**Comment by jimflores5** [comment]
Removed.  Thanks.
