### ISSUE TITLE
[consistency] 6.2.2 Syntax Errors

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#87]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/categories-of-errors.html#syntax-errors

## Issue

Looking at the "Try it" box, I find 2 syntax errors (missing quotes and missing half parenthesis). When you click the "repl.it" link, the starter code has missing quotes and both parentheses. 

## (Optional) Screenshow

![image](https://user-images.githubusercontent.com/13736167/60592336-0a819400-9d66-11e9-946d-3f62f44cd9d9.png)

**Comment by jimflores5** [comment]
Good catch.  Fixed in repl.it.
