### ISSUE TITLE
[grammar] 6.3.2 Code Highlighting

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#88]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/diagnosing-error-messages.html#syntax-errors-and-code-highlighting

## Issue

1) "give" should be "gives"
2) Below the screenshot of the code editor, "At the end of line 1" should be "At the end of Line 2". 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60593232-ede65b80-9d67-11e9-8aee-95f20f6fa2c0.png)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
