### ISSUE TITLE
[comment] 6.4 Error Types

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#89]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/error-types.html#error-types

## Issue

I really like the JavaScript Error Types table. Can you please add a simple definition (or at least the full name) of URI in the URIError description? I believe this is the first time readers encounter this term and can do their research easier if they want to learn more about this type of errors. 

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Provided the words behind the URI abbreviation. At this point, the students do not require a detailed discussion about the differences between URL and URI.
