### ISSUE TITLE
[grammar] 6.6.1 Start Small

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#90]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/how-to-avoid-debugging.html#start-small

## Issue

Missing period (.) at the end of the highlighted phrase. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60770864-62413780-a0a5-11e9-9189-817b5dad879b.png)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
