### ISSUE TITLE
[grammar] 6.7.3

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#92]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/asking-good-questions.html#where-have-you-looked-for-an-answer

## Issue

Redundant "the". 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60771023-3aeb6a00-a0a7-11e9-8dee-0e40d47f4802.png)

**Comment by jimflores5** [comment]
Removed extra 'the'.  Thanks.
