### ISSUE TITLE
[comment] 6.8 Exercises: Debugging

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#93]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/exercises.html

## Issue

This entire section, while super clever, can be very confusing to non-native English speakers in our class. While I was able to extract information necessary to solve the exercise problems on my own, I had to ask someone else to understand that it was a pirate parody. I am concerned about how students with English as a second language would feel when they could already be struggling with the coding concepts. 

A simple way to address this issue without diminishing too much of the humor might be to add a sentence at the beginning to provide some context, such as "The space shuttle has been attacked by a group of pirates who demand some help..." 

Another way is to explain explicitly that this is an imitation of pirates, (although please don't use the word "parody" - it is too specialized...) This would address the issue more fundamentallly but also make it a lot less funny. 

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by gildedgardenia** [comment]
Changed the wording to indicate that this is pirate talk! Let us know what you think!
