### ISSUE TITLE
[spelling] 6.8 Exercises

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#94]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/exercises.html#exercises-debugging

## Issue

"below" is misspelled. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60771360-9a984400-a0ac-11e9-8351-e157150fdb22.png)

**Comment by jimflores5** [comment]
Actually, the word is correct as 'bellow', which means to yell loudly.  Pirate talk is tricky, though.
