### ISSUE TITLE
[grammar] 7.3.1 Object Terminology

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#95]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/strings/strings-as-objects.html#object-terminology

## Issue

"features" as highlighted should be singular. 

## (Optional) Screenshow

(If helpful, add a screenshot.)
![image](https://user-images.githubusercontent.com/13736167/60776334-1ae09880-a0f1-11e9-8894-a033597cb7ba.png)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
