### ISSUE TITLE
[grammar] toLowerCase Examples

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#96]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/appendices/string-method-examples/toLowerCase-examples.html

## Issue

In the Warning box, "If" should be replaced with "When" (I believe). 

## (Optional) Screenshow

![image](https://user-images.githubusercontent.com/13736167/60779576-e1b02480-a100-11e9-96c0-78bd47d57095.png)

**Comment by jimflores5** [comment]
Fixed.  Thanks.
